<?php

namespace SmartCNAB\Support\Bank;

use SmartCNAB\Support\Bank\Bank;

/**
 * Bank Itau support class.
 */
class Itau extends Bank
{
    /**
     * Constants for returning occurrences statuses.
     */
    const OCCURRENCES_DISCHARGED = [9, 47, 59, 72];
    const OCCURRENCES_ENTRY = [2, 64];
    const OCCURRENCES_ERROR = [3, 15, 16, 17, 18];
    const OCCURRENCES_INSTRUCTION_CANCELED = [57];
    const OCCURRENCES_PAID = [6, 7, 8, 10];
    const OCCURRENCES_PROTESTED = [32];

    /**
     * Especies codes.
     *
     * @var array
     */
    protected static $especies = [
        '01' => 'Duplicata mercantil',
        '02' => 'Nota promissória',
        '03' => 'Nota de seguro',
        '04' => 'Mensalidade escolar',
        '05' => 'Recibo',
        '06' => 'Contrato',
        '07' => 'Cosseguros',
        '08' => 'Duplicata de serviço',
        '09' => 'Letra de câmbio',
        '13' => 'Nota de débitos',
        '15' => 'Documento de dívida',
        '16' => 'Encargos condominiais',
        '17' => 'Conta de prestação de serviços',
        // '18' => 'Boleto de proposta', // Not implemented yet
        '99' => 'Diversos',
    ];

    /**
     * Billing instruction.
     *
     * @var array
     */
    protected static $instructions = [
        '02' => 'Devolver após 05 dias do vencimento',
        '03' => 'Devolver após 30 dias do vencimento',
        '05' => 'Receber conforme instruções no próprio título',
        '06' => 'Devolver após 10 dias do vencimento',
        '07' => 'Devolver após 15 dias do vencimento',
        '08' => 'Devolver após 20 dias do vencimento',
        '09' => 'Protestar',
        '10' => 'Não protestar (inibe protesto, quando houver instrução permanente na conta corrente)',
        '11' => 'Devolver após 25 dias do vencimento',
        '12' => 'Devolver após 35 dias do vencimento',
        '13' => 'Devolver após 40 dias do vencimento',
        '14' => 'Devolver após 45 dias do vencimento',
        '15' => 'Devolver após 50 dias do vencimento',
        '16' => 'Devolver após 55 dias do vencimento',
        '17' => 'Devolver após 60 dias do vencimento',
        '18' => 'Devolver após 90 dias do vencimento',
        '19' => 'Não receber após 05 dias do vencimento',
        '20' => 'Não receber após 10 dias do vencimento',
        '21' => 'Não receber após 15 dias do vencimento',
        '22' => 'Não receber após 20 dias do vencimento',
        '23' => 'Não receber após 25 dias do vencimento',
        '24' => 'Não receber após 30 dias do vencimento',
        '25' => 'Não receber após 35 dias do vencimento',
        '26' => 'Não receber após 40 dias do vencimento',
        '27' => 'Não receber após 45 dias do vencimento',
        '28' => 'Não receber após 50 dias do vencimento',
        '29' => 'Não receber após 55 dias do vencimento',
        '30' => 'Importância de desconto por dia',
        '31' => 'Não receber após 60 dias do vencimento',
        '32' => 'Não receber após 90 dias do vencimento',
        '33' => 'Conceder abatimento ref. à PIS-PASEP/COFIN/CSSL, mesmo após vencimento',
        '34' => 'Protestar após xx dias corridos do vencimento',
        '35' => 'Protestar após xx dias úteis do vencimento',
        '37' => 'Receber até o último dia do mês de vencimento',
        '38' => 'Conceder desconto mesmo após vencimento',
        '39' => 'Não receber após o vencimento',
        '40' => 'Conceder desconto conforme nota de crédito',
        '42' => 'Protesto para fins falimentares',
        '43' => 'Sujeito a protesto se não for pago no vencimento',
        '44' => 'Importância por dia de atraso a partir de ddmmaa',
        '45' => 'Tem dia da graça',
        '47' => 'Dispensar juros/comissão de permanência',
        '51' => 'Receber somente com a parcela anterior quitada',
        '52' => 'Efetuar o pagamento somente através deste boleto e na rede bancária',
        '54' => 'Após vencimento pagável somente na empresa',
        '57' => 'Somar valor do título ao valor do campo mora/multa caso exista',
        '58' => 'Devolver após 365 dias de vencido',
        '59' => 'Cobrança negociada. pagável somente por este boleto na rede bancária',
        '61' => 'Título entregue em penhor em favor do beneficiário acima',
        '62' => 'Título transferido a favor do beneficiário',
        '66' => 'Entrada em negativação expressa (imprime: sujeito a negativação após o vencimento)',
        '67' => 'Não negativar (inibe a entrada em negativação expressa)',
        '78' => 'Valor da ida engloba multa de 10% pro rata',
        '79' => 'Cobrar juros após 15 dias da emissão (para títulos com vencimento à vista)',
        '80' => 'Pagamento em cheque: somente receber com cheque de emissão do pagador',
        '83' => 'Operação ref a vendor',
        '84' => 'Após vencimento consultar a agência beneficiário',
        '86' => 'Antes do vencimento ou após 15 dias, pagável somente em nossa sede',
        '88' => 'Não receber antes do vencimento',
        '90' => 'No vencimento pagável em qualquer agência bancária',
        '91' => 'Não receber após xx dias do vencimento',
        '92' => 'Devolver após xx dias do vencimento',
        '93' => 'Mensagens nos boletos com 30 posições',
        '94' => 'Mensagens nos boletos com 40 posições',
        '98' => 'Duplicata / Número fatura',
    ];

    /**
     * Motives codes.
     *
     * @var array
     */
    protected static $motives = [
        '02' => [
            '01' => 'CEP sem atendimento de protesto no momento.',
            '02' => 'Estado com determinação legal que impede a inscrição de inadimplentes nos cadastros de proteção ao crédito no prazo solicitado – Prazo superior ao solicitado.',
        ],
        '03' => [
            '03' => 'Ag. cobradora: CEP sem atendimento de protesto no momento.',
            '04' => 'Estado: Sigla do estado inválida.',
            '05' => 'Data vencimento: Prazo da operação menor que prazo mínimo ou maior que o máximo.',
            '07' => 'Valor do título: Valor do título maior que 10.000.000,00.',
            '08' => 'Nome do pagador: Não informado ou deslocado.',
            '09' => 'Agencia/conta: Agência encerrada.',
            '10' => 'Logradouro: Não informado ou deslocado.',
            '11' => 'CEP: CEP não numérico ou CEP inválido.',
            '12' => 'Sacador/avalista: Nome não informado ou deslocado (bancos correspondentes).',
            '13' => 'Estado/CEP: CEP incompatível com a sigla do estado.',
            '14' => 'Nosso número: Nosso número já registrado no cadastro do banco ou fora da faixa.',
            '15' => 'Nosso número: Nosso número em duplicidade no mesmo movimento.',
            '18' => 'Data de entrada: Data de entrada inválida para operar com esta carteira.',
            '19' => 'Ocorrência: Ocorrência inválida.',
            '21' => 'Ag. cobradora: Carteira não aceita depositária correspondente/estado da agência diferente do estado do pagador/Ag. cobradora não consta no cadastro ou encerrando.',
            '22' => 'Carteira: Carteira não permitida (necessário cadastrar faixa livre).',
            '26' => 'Agência/conta: Agência/conta não liberada para operar com cobrança.',
            '27' => 'Cnpj inapto: Cnpj do beneficiário inapto/devolução de título em garantia.',
            '29' => 'Código empresa: Categoria da conta inválida.',
            '30' => 'Entrada bloqueada: Entradas bloqueadas, conta suspensa em cobrança.',
            '31' => 'Agência/conta: Conta não tem permissão para protestar (contate seu gerente).',
            '35' => 'Valor do iof: Iof maior que 5%.',
            '36' => 'Qtdade de moeda: Quantidade de moeda incompatível com valor do título.',
            '37' => 'CNPJ/CPF do pagador: Não numérico ou igual a zeros.',
            '42' => 'Nosso número: Nosso número fora de faixa.',
            '52' => 'Ag. cobradora: Empresa não aceita banco correspondente.',
            '53' => 'Ag. cobradora: Empresa não aceita banco correspondente - cobrança mensagem.',
            '54' => 'Data de vencto: Banco correspondente - título com vencimento inferior a 15 dias.',
            '55' => 'Dep/bco corresp: CEP não pertence à depositária informada.',
            '56' => 'Dt vencto/bco corresp: Vencto superior a 180 dias da data de entrada.',
            '57' => 'Data de vencto: CEP só depositária bco do brasil com vencto inferior a 8 dias.',
            '60' => 'Abatimento: Valor do abatimento inválido.',
            '61' => 'Juros de mora: Juros de mora maior que o permitido.',
            '62' => 'Desconto: Valor do desconto maior que valor do título.',
            '63' => 'Desconto de antecipação: Valor da importância por dia de desconto (idd) não permitido.',
            '64' => 'Data de emissão: Data de emissão do título inválida.',
            '65' => 'Taxa financto: Taxa inválida (vendor).',
            '66' => 'Data de vencto: Invalida/fora de prazo de operação (mínimo ou máximo).',
            '67' => 'Valor/qtidade: Valor do título/quantidade de moeda inválido.',
            '68' => 'Carteira: Carteira inválida ou não cadastrada no intercâmbio da cobrança.',
            '69' => 'Carteira: Carteira inválida para títulos com rateio de crédito.',
            '70' => 'Agência/conta: Beneficiário não cadastrado para fazer rateio de crédito.',
            '78' => 'Agência/conta: Duplicidade de agência/conta beneficiária do rateio de crédito.',
            '80' => 'Agência/conta: Quantidade de contas beneficiárias do rateio maior do que o permitido (máximo de 30 contas por título).',
            '81' => 'Agência/conta: Conta para rateio de crédito inválida / não pertence ao itaú.',
            '82' => 'Desconto/abatimento: Desconto/abatimento não permitido para títulos com rateio de crédito.',
            '83' => 'Valor do título: Valor do título menor que a soma dos valores estipulados para rateio.',
            '84' => 'Agência/conta: Agência/conta beneficiária do rateio é a centralizadora de crédito do beneficiário.',
            '85' => 'Agência/conta: Agência/conta do beneficiário é contratual / rateio de crédito não permitido.',
            '86' => 'Tipo de valor: Código do tipo de valor inválido / não previsto para títulos com rateio de crédito.',
            '87' => 'Agência/conta: Registro tipo 4 sem informação de agências/contas beneficiárias do rateio.',
            '90' => 'Nro da linha: Cobrança mensagem - número da linha da mensagem inválido ou quantidade de linhas excedidas.',
            '97' => 'Sem mensagem: Cobrança mensagem sem mensagem (só de campos fixos), porém com registro do tipo 7 ou 8.',
            '98' => 'Flash inválido: Registro mensagem sem flash cadastrado ou flash informado diferente do cadastrado.',
            '99' => 'Flash inválido: Conta de cobrança com flash cadastrado e sem registro de mensagem correspondente.',
        ],
        '15' => [
            '01' => 'Carteira/No número não numérico.',
            '04' => 'Nosso número em duplicidade no mesmo movimento.',
            '05' => 'Solicitação de baixa para título já baixado ou liquidado.',
            '06' => 'Solicitação de baixa para título não registrado no sistema.',
            '07' => 'Cobrança prazo curto – solicitação de baixa p/ título não registrado no sistema.',
            '08' => 'Solicitação de baixa para título em floating.',
            '10' => 'Valor do titulo faz parte de garantia de emprestimo.',
            '11' => 'Pago através do sispag por crédito em c/c e não baixado.',
        ],
        '16' => [
            '01' => 'Instrução/ocorrência não existente.',
            '03' => 'Conta não tem permissão para protestar (contate seu gerente).',
            '06' => 'Nosso número igual a zeros.',
            '09' => 'CNPJ/CPF do sacador/avalista inválido.',
            '10' => 'Valor do abatimento igual ou maior que o valor do título.',
            '11' => 'Segunda instrução/ocorrência não existente.',
            '14' => 'Registro em duplicidade.',
            '15' => 'CNPJ/CPF informado sem nome do sacador/avalista.',
            '19' => 'Valor do abatimento maior que 90% do valor do título.',
            '20' => 'Existe sustacao de protesto pendente para o titulo.',
            '21' => 'Título não registrado no sistema.',
            '22' => 'Título baixado ou liquidado.',
            '23' => 'Instrução não aceita.',
            '24' => 'Instrução incompatível – existe instrução de protesto para o título.',
            '25' => 'Instrução incompatível – não existe instrução de protesto para o título.',
            '26' => 'Instrução não aceita por já ter sido emitida a ordem de protesto ao cartório.',
            '27' => 'Instrução não aceita por não ter sido emitida a ordem de protesto ao cartório.',
            '28' => 'Já existe uma mesma instrução cadastrada anteriormente para o título.',
            '29' => 'Valor líquido + valor do abatimento diferente do valor do título registrado.',
            '30' => 'Existe uma instrução de não protestar ativa para o título.',
            '31' => 'Existe uma ocorrência do pagador que bloqueia a instrução.',
            '32' => 'Depositária do título = 9999 ou carteira não aceita protesto.',
            '33' => 'Alteração de vencimento igual à registrada no sistema ou que torna o título vencido.',
            '34' => 'Instrução de emissão de aviso de cobrança para título vencido antes do vencimento.',
            '35' => 'Solicitação de cancelamento de instrução inexistente.',
            '36' => 'Título sofrendo alteração de controle (agência/conta/carteira/nosso número).',
            '37' => 'Instrução não permitida para a carteira.',
            '38' => 'Instrução não permitida para título com rateio de crédito.',
            '40' => 'Instrução incompatível – não existe instrução de negativação expressa para o título.',
            '41' => 'Instrução não permitida – título com entrada em negativação expressa.',
            '42' => 'Instrução não permitida – título com negativação expressa concluída.',
            '43' => 'Prazo inválido para negativação expressa – mínimo: 02 dias corridos após o vencimento.',
            '45' => 'Instrução incompatível para o mesmo título nesta data.',
            '47' => 'Instrução não permitida – espécie inválida.',
            '48' => 'Dados do pagador inválidos (CPF/CNPJ/nome).',
            '49' => 'Dados do endereço do pagador inválidos.',
            '50' => 'Data de emissão do título inválida.',
            '51' => 'Instrução não permitida – título com negativação expressa agendada.',
        ],
        '17' => [
            '02' => 'Agência cobradora inválida ou com o mesmo conteúdo.',
            '04' => 'Sigla do estado inválida.',
            '05' => 'Data de vencimento inválida ou com o mesmo conteúdo.',
            '06' => 'Valor do título com outra alteração simultânea.',
            '08' => 'Nome do pagador com o mesmo conteúdo.',
            '09' => 'Agência/conta incorreta.',
            '11' => 'CEP inválido.',
            '12' => 'Número inscrição inválido do sacador avalista.',
            '13' => 'Seu número com o mesmo conteúdo.',
            '16' => 'Abatimento/alteração do valor do título ou solicitação de baixa bloqueada.',
            '20' => 'Espécie inválida.',
            '21' => 'Agência cobradora não consta no cadastro de depositária ou em encerramento.',
            '23' => 'Data de emissão do título inválida ou com mesmo conteúdo.',
            '41' => 'Campo aceite inválido ou com mesmo conteúdo.',
            '42' => 'Alteração inválida para título vencido.',
            '43' => 'Alteração bloqueada – vencimento já alterado.',
            '53' => 'Instrução com o mesmo conteúdo.',
            '54' => 'Data vencimento para bancos correspondentes inferior ao aceito pelo banco.',
            '55' => 'Alterações iguais para o mesmo controle (agência/conta/carteira/nosso número).',
            '56' => 'CNPJ/CPF inválido não numérico ou zerado.',
            '57' => 'Prazo de vencimento inferior a 15 dias.',
            '60' => 'Valor de iof – alteração não permitida para carteiras de n.s. – moeda variável.',
            '61' => 'Título já baixado ou liquidado ou não existe título correspondente no sistema.',
            '66' => 'Alteração não permitida para carteiras de notas de seguros – moeda variável.',
            '67' => 'Nome inválido do sacador avalista.',
            '72' => 'Endereço inválido – sacador avalista.',
            '73' => 'Bairro inválido – sacador avalista.',
            '74' => 'Cidade inválida – sacador avalista.',
            '75' => 'Sigla estado inválido – sacador avalista.',
            '76' => 'CEP inválido – sacador avalista.',
            '81' => 'Alteração bloqueada – título com negativação expressa / protesto.',
            '87' => 'Alteração bloqueada – título com rateio de crédito.',
        ],
        '18' => [
            '16' => 'Abatimento/alteração do valor do título ou solicitação de baixa bloqueados.',
            '40' => 'Não aprovada devido ao impacto na elegibilidade de garantias.',
            '41' => 'Automaticamente rejeitada.',
            '42' => 'Confirma recebimento de instrução – pendente de análise.',
        ],
        '24' => [
            '1610' => 'Documentação solicitada ao beneficiário.',
            '3103' => 'Insuficiencia de dados no modelo 4006.',
            '3111' => 'Sustação solicitada ag. beneficiário.',
            '3129' => 'Titulo nao enviado a cartorio.',
            '3137' => 'Aguardar um dia util apos o vencto para protestar.',
            '3145' => 'DM/DMI sem comprovante autenticado ou declaracao.',
            '3152' => 'Falta contrato de serv. (ag. ced: enviar).',
            '3160' => 'Nome do pagador incompleto/incorreto.',
            '3178' => 'Nome do beneficiário incompleto/incorreto.',
            '3186' => 'Nome do sacador incompleto/incorreto.',
            '3194' => 'Tit aceito: identif assinante do cheq.',
            '3202' => 'Tit aceito: rasurado ou rasgado.',
            '3210' => 'Tit aceito: falta tit.(ag.ced:enviar).',
            '3228' => 'Atos da corregedoria estadual.',
            '3236' => 'Nao foi possivel efetuar o protesto.',
            '3244' => 'Protesto sustado / beneficiário não entregou a documentação.',
            '3251' => 'Documentacao irregular.',
            '3269' => 'Data de emissão do título inválida / irregular.',
            '3277' => 'Especie invalida para protesto.',
            '3285' => 'Praça não atendida pela rede bancária.',
            '3293' => 'Centralizadora de protesto nao recebeu a documentacao.',
            '3301' => 'CNPJ/CPF do pagador inválido / incorreto.',
            '3319' => 'Sacador/avalista e pessoa física.',
            '3327' => 'Cep do pagador incorreto.',
            '3335' => 'Depositária incompatível com cep do pagador.',
            '3343' => 'CNPJ/CPF sacador invalido / incorreto.',
            '3350' => 'Endereço do pagador insuficiente.',
            '3368' => 'Praça pagto incompatível com endereço.',
            '3376' => 'Falta número/espécie do título.',
            '3384' => 'Título aceito s/ assinatura do sacador.',
            '3392' => 'Título aceito s/ endosso beneficiário ou irregular.',
            '3400' => 'Título sem local ou data de emissão.',
            '3418' => 'Título aceito com valor extenso diferente do numérico.',
            '3426' => 'Título aceito definir espécie da duplicata.',
            '3434' => 'Data emissão posterior ao vencimento.',
            '3442' => 'Título aceito documento não protestável.',
            '3459' => 'Título aceito extenso vencimento irregular.',
            '3467' => 'Título aceito falta nome favorecido.',
            '3475' => 'Título aceito falta praça de pagamento.',
            '3483' => 'Título aceito falta cpf assinante cheque.',
            '3491' => 'Falta número do título (seu número).',
            '3509' => 'Cartório da praça com atividade suspensa.',
            '3517' => 'Data apresentacao menor que a data vencimento.',
            '3525' => 'Falta comprovante da prestacao de servico.',
            '3533' => 'CNPJ/CPF pagador incompativel c/ tipo de documento.',
            '3541' => 'CNPJ/CPF sacador incompativel c/ especie.',
            '3558' => 'Tit aceito: s/ assinatura do pagador.',
            '3566' => 'Falta data de emissao do titulo.',
            '3574' => 'Saldo maior que o valor do titulo.',
            '3582' => 'Tipo de endosso invalido.',
            '3590' => 'Devolvido por ordem judicial.',
            '3608' => 'Dados do titulo nao conferem com disquete.',
            '3616' => 'Pagador e sacador avalista são a mesma pessoa.',
            '3624' => 'Comprovante ilegivel para conferencia e microfilmagem.',
            '3632' => 'Confirmar se sao dois emitentes.',
            '3640' => 'Endereco do pagador igual ao do sacador ou do portador.',
            '3657' => 'Endereco do beneficiário incompleto ou nao informado.',
            '3665' => 'Endereco do emitente no cheque igual ao do banco pagador.',
            '3673' => 'Falta motivo da devolucao no cheque ou ilegivel.',
            '3681' => 'Titulo com direito de regresso vencido.',
            '3699' => 'Titulo apresentado em duplicidade.',
            '3707' => 'Lc emitida manualmente (titulo do banco/ca).',
            '3715' => 'Nao protestar lc (titulo do banco/ca).',
            '3723' => 'Eliminar o protesto da lc (titulo do banco/ca).',
            '3731' => 'Titulo ja protestado.',
            '3749' => 'Titulo – falta traducao por tradutor publico.',
            '3756' => 'Falta declaracao de saldo assinada no titulo.',
            '3764' => 'Contrato de cambio – falta conta grafica.',
            '3772' => 'Pagador falecido.',
            '3780' => 'Especie de titulo que o banco nao protesta.',
            '3798' => 'Ausencia do documento fisico.',
            '3806' => 'Ordem de protesto sustada, motivo.',
            '3814' => 'Pagador apresentou quitação do título.',
            '3822' => 'Pagador irá negociar com beneficiário.',
            '3830' => 'Cpf incompatível com a espécie do título.',
            '3848' => 'Título de outra jurisdição territorial.',
            '3855' => 'Título com emissão anterior a concordata do pagador.',
            '3863' => 'Pagador consta na lista de falência.',
            '3871' => 'Apresentante não aceita publicação de edital.',
            '3889' => 'Cartório com problemas operacionais.',
            '3897' => 'Envio de titulos para protesto temporariamente paralisado.',
            '3905' => 'Beneficiário com conta em cobranca suspensa.',
            '3913' => 'Cep do pagador e uma caixa postal.',
            '3921' => 'Espécie não protestável no estado.',
            '3939' => 'Falta endereço ou documento do sacador avalista.',
            '3947' => 'Corrigir a especie do titulo.',
            '3954' => 'Erro de preenchimento do titulo.',
            '3962' => 'Valor divergente entre titulo e comprovante.',
            '3970' => 'Condominio nao pode ser protestado p/ fins falimentares.',
            '3988' => 'Vedada intimacao por edital para protesto falimentar.',
        ],
        '25' => [
            '1313' => 'Solicita a prorrogação do vencimento para:',
            '1321' => 'Solicita a dispensa dos juros de mora.',
            '1339' => 'Não recebeu a mercadoria.',
            '1347' => 'A mercadoria chegou atrasada.',
            '1354' => 'A mercadoria chegou avariada.',
            '1362' => 'A mercadoria chegou incompleta.',
            '1370' => 'A mercadoria não confere com o pedido.',
            '1388' => 'A mercadoria está à disposição.',
            '1396' => 'Devolveu a mercadoria.',
            '1404' => 'Não recebeu a fatura.',
            '1412' => 'A fatura está em desacordo com a nota fiscal.',
            '1420' => 'O pedido de compra foi cancelado.',
            '1438' => 'A duplicata foi cancelada.',
            '1446' => 'Que nada deve ou comprou.',
            '1453' => 'Que mantém entendimentos com o sacador.',
            '1461' => 'Que pagará o título em:',
            '1479' => 'Que pagou o título diretamente ao beneficiário em:',
            '1487' => 'Que pagará o título diretamente ao beneficiário em:',
            '1495' => 'Que o vencimento correto é:',
            '1503' => 'Que tem desconto ou abatimento de:',
            '1719' => 'Pagador não foi localizado; confirmar endereço.',
            '1727' => 'Pagador está em regime de concordata.',
            '1735' => 'Pagador está em regime de falência.',
            '1750' => 'Pagador se recusa a pagar juros bancários.',
            '1768' => 'Pagador se recusa a pagar comissão de permanência.',
            '1776' => 'Não foi possível a entrega do boleto ao pagador.',
            '1784' => 'Boleto não entregue, mudou-se / desconhecido.',
            '1792' => 'Boleto não entregue, cep errado / incompleto.',
            '1800' => 'Boleto não entregue, número não existe/endereço incompleto.',
            '1818' => 'Boleto não retirado pelo pagador. reenviado pelo correio para carteiras com emissão pelo banco.',
            '1826' => 'Endereço de e-mail inválido/cobrança mensagem. boleto enviado pelo correio.',
            '1834' => 'Boleto dda, divida reconhecida pelo pagador.',
            '1842' => 'Boleto dda, divida não reconhecida pelo pagador.',
        ],
        '57' => [
            '1156' => 'Não protestar.',
            '2261' => 'Dispensar juros/comissão de permanência.',
        ],
        '69' => [
            '11' => 'Cheque sem fundos – primeira apresentação.',
            '12' => 'Cheque sem fundos – segunda apresentação.',
            '13' => 'Conta encerrada.',
            '14' => 'Prática espúria.',
            '20' => 'Folha de cheque cancelada por solicitação do correntista.',
            '21' => 'Contra-ordem (ou revogação) ou oposição (ou sustação) ao pagamento pelo emitente ou pelo portador.',
            '22' => 'Divergência ou insuficiência de assinatura.',
            '23' => 'Cheques emitidos por entidades e órgãos da administração pública federal direta e indireta, em desacordo com os requisitos constantes do artigo 74, § 2o, do decreto-lei No 200, de 25.02.1967.',
            '24' => 'Bloqueio judicial ou determinação do banco central do brasil.',
            '25' => 'Cancelamento de talonário pelo banco pagador.',
            '28' => 'Contra-ordem (ou revogação) ou oposição (ou sustação) ao pagamento ocasionada por furto ou roubo.',
            '29' => 'Cheque bloqueado por falta de confirmação do recebimento do talonário pelo correntista.',
            '30' => 'Furto ou roubo de malotes.',
            '31' => 'Erro formal (sem data de emissão, com o mês grafado numericamente, ausência de assinatura, não-registro do valor por extenso).',
            '32' => 'Ausência ou irregularidade na aplicação do carimbo de compensação.',
            '33' => 'Divergência de endosso.',
            '34' => 'Cheque apresentado por estabelecimento bancário que não o indicado no cruzamento em preto, sem o endosso-mandato.',
            '35' => 'Cheque fraudado, emitido sem prévio controle ou responsabilidade do estabelecimento bancário (“cheque universal”), ou ainda com adulteração da praça sacada.',
            '36' => 'Cheque emitido com mais de um endosso.',
            '40' => 'Moeda inválida.',
            '41' => 'Cheque apresentado a banco que não o pagador.',
            '42' => 'Cheque não-compensável na sessão ou sistema de compensação em que foi apresentado.',
            '43' => 'Cheque, devolvido anteriormente pelos motivos 21, 22, 23, 24, 31 ou 34, não-passível de reapresentação em virtude de persistir o motivo da devolução.',
            '44' => 'Cheque prescrito.',
            '45' => 'Cheque emitido por entidade obrigada a realizar movimentação e utilização de recursos financeiros do tesouro nacional mediante ordem bancária.',
            '48' => 'Cheque de valor superior ao estabelecido, emitido sem a identificação do beneficiário, devendo ser devolvido a qualquer tempo.',
            '49' => 'Remessa nula, caracterizada pela reapresentação de cheque devolvido pelos motivos 12, 13, 14, 20, 25, 28, 30, 35, 43, 44 e 45, podendo a sua devolução ocorrer a qualquer tempo.',
        ],
        '74' => [
            '6007' => 'Inclusão bloqueada face a determinação judicial.',
            '6015' => 'Inconsistências nas informações de endereço.',
            '6023' => 'Título já decursado.',
            '6031' => 'Inclusão condicionada a apresentação de documento de dívida.',
            '6163' => 'Exclusão não permitida, registro suspenso.',
            '6171' => 'Exclusão para registro inexistente.',
            '6379' => 'Rejeição por dado(s) inconsistente(s).',
        ],
        '79' => [
            '6049' => 'Informação dos correios – Mudou-se.',
            '6056' => 'Informação dos correios – Devolvido por informação prestada pelo sindico ou porteiro.',
            '6064' => 'Informação dos correios – Devolvido por inconsistência no endereço.',
            '6072' => 'Informação dos correios – Desconhecido.',
            '6080' => 'Informação dos correios – Recusado.',
            '6098' => 'Informação dos correios – Ausente.',
            '6106' => 'Informação dos correios – Não procurado.',
            '6114' => 'Informação dos correios – Falecido.',
            '6122' => 'Informação dos correios – Não especificado.',
            '6130' => 'Informação dos correios – Caixa postal inexistente.',
            '6148' => 'Informação dos correios – Devolução do comunicado do correio.',
            '6155' => 'Informação dos correios – Outros motivos.',
            '6478' => 'AR - Entregue com sucesso.',
            '6486' => 'Inclusao para registro ja existente/recusado.',
            '6494' => 'AR - Carta extraviada e não entregue.',
            '6502' => 'AR - Carta roubada e não entregue.',
            '6510' => 'AR - Ausente - Encaminhado para entrega interna.',
            '6528' => 'AR inutilizado - Não retirado nos correios após 3 tentativas.',
            '6536' => 'AR - Endereco incorreto.',
            '6544' => 'AR - Nao procurado – Devolvido ao remetente.',
            '6551' => 'AR - Não entregue por falta de apresentar documento com foto.',
            '6569' => 'AR - Mudou-se.',
            '6577' => 'AR - Desconhecido.',
            '6585' => 'AR - Recusado.',
            '6593' => 'AR - Endereco insuficiente.',
            '6601' => 'AR - Nao existe o numero indicado.',
            '6618' => 'AR - Ausente.',
            '6627' => 'AR - Carta nao procurada na unidade dos correios.',
            '6635' => 'AR - Falecido.',
            '6643' => 'AR - Devido a devolucao do comunicado do correio.',
        ],
    ];

    /**
     * Remittance occurrences codes.
     *
     * @var array
     */
    protected static $remittanceOccurrences = [
        '01' => 'Remessa',
        '02' => 'Pedido de baixa',
        '04' => 'Concessão de abatimento (indicador 12.5)',
        '05' => 'Cancelamento de abatimento',
        '06' => 'Alteração do vencimento',
        '07' => 'Alteração do uso da empresa',
        '08' => 'Alteração do seu número',
        '09' => 'Protestar',
        '10' => 'Não protestar',
        '11' => 'Protesto para fins falimentares',
        '18' => 'Sustar o protesto',
        '30' => 'Exclusão de sacador avalista',
        '31' => 'Alteração de outros dados',
        '34' => 'Baixa por ter sido pago diretamente ao beneficiário',
        '35' => 'Cancelamento de instrução',
        '37' => 'Alteração do vencimento e sustar protesto',
        '38' => 'Beneficiário não concorda com alegação do pagador',
        '47' => 'Beneficiário solicita dispensa de juros',
        '49' => 'Alteração de dados extras (registro de multa)',
        '66' => 'Entrada em negativação expressa',
        '67' => 'Não negativar (inibe a entrada em negativação expressa)',
        '68' => 'Excluir negativação expressa (até 15 dias corridos após a entrada em negativação expressa)',
        '69' => 'Cancelar negativação expressa (após título ter sido negativado)',
        '93' => 'Descontar títulos encaminhados no dia',
    ];

    /**
     * Return occurrences codes.
     *
     * @var array
     */
    protected static $returnOccurrences = [
        '02' => 'Entrada confirmada com possibilidade de mensagem',
        '03' => 'Entrada rejeitada',
        '04' => 'Alteração de dados – nova entrada ou alteração/exclusão de dados acatada',
        '05' => 'Alteração de dados – baixa',
        '06' => 'Liquidação normal',
        '07' => 'Liquidação parcial – cobrança inteligente (b2b)',
        '08' => 'Liquidação em cartório',
        '09' => 'Baixa simples',
        '10' => 'Baixa por ter sido liquidado',
        '11' => 'Em ser (só no retorno mensal)',
        '12' => 'Abatimento concedido',
        '13' => 'Abatimento cancelado',
        '14' => 'Vencimento alterado',
        '15' => 'Baixas rejeitadas',
        '16' => 'Instruções rejeitadas',
        '17' => 'Alteração/exclusão de dados rejeitados',
        '18' => 'Cobrança contratual – instruções/alterações rejeitadas/pendentes',
        '19' => 'Confirma recebimento de instrução de protesto',
        '20' => 'Confirma recebimento de instrução de sustação de protesto /tarifa',
        '21' => 'Confirma recebimento de instrução de não protestar',
        '23' => 'Título enviado a cartório/tarifa',
        '24' => 'Instrução de protesto rejeitada/sustada/pendente',
        '25' => 'Alegações do pagador',
        '26' => 'Tarifa de aviso de cobrança',
        '27' => 'Tarifa de extrato posição (b40x)',
        '28' => 'Tarifa de relação das liquidações',
        '29' => 'Tarifa de manutenção de títulos vencidos',
        '30' => 'Débito mensal de tarifas (para entradas e baixas)',
        '32' => 'Baixa por ter sido protestado',
        '33' => 'Custas de protesto',
        '34' => 'Custas de sustação',
        '35' => 'Custas de cartório distribuidor',
        '36' => 'Custas de edital',
        '37' => 'Tarifa de emissão de boleto/tarifa de envio de duplicata',
        '38' => 'Tarifa de instrução',
        '39' => 'Tarifa de ocorrências',
        '40' => 'Tarifa mensal de emissão de boleto/tarifa mensal de envio de duplicata',
        '41' => 'Débito mensal de tarifas – extrato de posição (b4ep/b4ox)',
        '42' => 'Débito mensal de tarifas – outras instruções',
        '43' => 'Débito mensal de tarifas – manutenção de títulos vencidos',
        '44' => 'Débito mensal de tarifas – outras ocorrências',
        '45' => 'Débito mensal de tarifas – protesto',
        '46' => 'Débito mensal de tarifas – sustação de protesto',
        '47' => 'Baixa com transferência para desconto',
        '48' => 'Custas de sustação judicial',
        '51' => 'Tarifa mensal ref a entradas bancos correspondentes na carteira',
        '52' => 'Tarifa mensal baixas na carteira',
        '53' => 'Tarifa mensal baixas em bancos correspondentes na carteira',
        '54' => 'Tarifa mensal de liquidações na carteira',
        '55' => 'Tarifa mensal de liquidações em bancos correspondentes na carteira',
        '56' => 'Custas de irregularidade',
        '57' => 'Instrução cancelada',
        '59' => 'Baixa por crédito em c/c através do sispag',
        '60' => 'Entrada rejeitada carnê',
        '61' => 'Tarifa emissão aviso de movimentação de títulos (2154)',
        '62' => 'Débito mensal de tarifa – aviso de movimentação de títulos (2154)',
        '63' => 'Título sustado judicialmente',
        '64' => 'Entrada confirmada com rateio de crédito',
        '65' => 'Pagamento com cheque – aguardando compensação',
        '69' => 'Cheque devolvido',
        '71' => 'Entrada registrada, aguardando avaliação',
        '72' => 'Baixa por crédito em c/c através do sispag sem título correspondente',
        '73' => 'Confirmação de entrada na cobrança simples – entrada não aceita na cobrança contratual',
        '74' => 'Instrução de negativação expressa rejeitada',
        '75' => 'Confirmação de recebimento de instrução de entrada em negativação expressa',
        '76' => 'Cheque compensado',
        '77' => 'Confirmação de recebimento de instrução de exclusão de entrada em negativação expressa',
        '78' => 'Confirmação de recebimento de instrução de cancelamento de negativação expressa',
        '79' => 'Negativação expressa informacional',
        '80' => 'Confirmação de entrada em negativação expressa – tarifa',
        '82' => 'Confirmação do cancelamento de negativação expressa – tarifa',
        '83' => 'Confirmação de exclusão de entrada em negativação expressa por liquidação – tarifa',
        '85' => 'Tarifa por boleto (até 03 envios) cobrança ativa eletrônica',
        '86' => 'Tarifa email cobrança ativa eletrônica',
        '87' => 'Tarifa sms cobrança ativa eletrônica',
        '88' => 'Tarifa mensal por boleto (até 03 envios) cobrança ativa eletrônica',
        '89' => 'Tarifa mensal email cobrança ativa eletrônica',
        '90' => 'Tarifa mensal sms cobrança ativa eletrônica',
        '91' => 'Tarifa mensal de exclusão de entrada de negativação expressa',
        '92' => 'Tarifa mensal de cancelamento de negativação expressa',
        '93' => 'Tarifa mensal de exclusão de negativação expressa por liquidação',
    ];

    /**
     * Return the default state of info.
     *
     * @return \StdClass
     */
    public function defaults()
    {
        return (object) [
            'especie' => '01',
            'instruction1' => '02',
            'instruction2' => '00',
        ];
    }
}
