<?php

namespace SmartCNAB\Support\Bank;

/**
 * Bank Itau support class.
 */
class Itau
{
    /**
     * Occurrence codes
     */
    const OCURR_REMESSA = 1;
    const OCURR_PEDIDO_DE_BAIXA = 2;
    const OCURR_CONCESSAO_DE_ABATIMENTO_IND_12_5 = 4;
    const OCURR_CANCELAMENTO_DE_ABATIMENTO = 5;
    const OCURR_ALTERACAO_DO_VENCIMENTO = 6;
    const OCURR_ALTERACAO_DO_USO_DA_EMPRESA = 7;
    const OCURR_ALTERACAO_DO_SEU_NUMERO = 8;
    const OCURR_PROTESTAR = 9;
    const OCURR_NAO_PROTESTAR = 10;
    const OCURR_PROTESTO_PARA_FINS_FALIMENTARES = 11;
    const OCURR_SUSTAR_O_PROTESTO = 18;
    const OCURR_EXCLUSAO_DE_SACADOR_AVALISTA = 30;
    const OCURR_ALTERACAO_DE_OUTROS_DADOS = 31;
    const OCURR_BAIXA_POR_TER_SIDO_PAGO_DIRETAMENTE_AO_BENEFICIARIO = 34;
    const OCURR_CANCELAMENTO_DE_INSTRUCAO = 35;
    const OCURR_ALTERACAO_DO_VENCIMENTO_E_SUSTAR_PROTESTO = 37;
    const OCURR_BENEFICIARIO_NAO_CONCORDA_COM_ALEGACAO_DO_PAGADOR = 38;
    const OCURR_BENEFICIARIO_SOLICITA_DISPENSA_DE_JUROS = 47;
    const OCURR_ALTERACAO_DE_DADOS_EXTRAS_REGISTRO_DE_MULTA = 49;
    const OCURR_ENTRADA_EM_NEGATIVACAO_EXPRESSA = 66;
    const OCURR_NAO_NEGATIVAR_INIBE_A_ENTRADA_EM_NEGATIVACAO_EXPRESSA = 67;
    const OCURR_EXCLUIR_NEGATIVACAO_EXPRESSA_ATE_15_DIAS_CORRIDOS_APOS_A_ENTRADA_EM_NEGATIVACAO_EXPRESSA = 68;
    const OCURR_CANCELAR_NEGATIVACAO_EXPRESSA_APOS_TITULO_TER_SIDO_NEGATIVADO = 69;
    const OCURR_DESCONTAR_TITULOS_ENCAMINHADOS_NO_DIA = 93;

    /**
     * Especies codes
     */
    const ESP_DUPLICATA_MERCANTIL = 1;
    const ESP_NOTA_PROMISSORIA = 2;
    const ESP_NOTA_DE_SEGURO = 3;
    const ESP_MENSALIDADE_ESCOLAR = 4;
    const ESP_RECIBO = 5;
    const ESP_CONTRATO = 6;
    const ESP_COSSEGUROS = 7;
    const ESP_DUPLICATA_DE_SERVICO = 8;
    const ESP_LETRA_DE_CAMBIO = 9;
    const ESP_NOTA_DE_DEBITOS = 13;
    const ESP_DOCUMENTO_DE_DIVIDA = 15;
    const ESP_ENCARGOS_CONDOMINIAIS = 16;
    const ESP_CONTA_DE_PRESTACAO_DE_SERVICOS = 17;
    // const ESP_BOLETO_DE_PROPOSTA = 18; // Not implemented
    const ESP_DIVERSOS = 99;

    /**
     * Billing instruction
     */
    const INST_DEVOLVER_APOS_05_DIAS_DO_VENCIMENTO = 2;
    const INST_DEVOLVER_APOS_30_DIAS_DO_VENCIMENTO = 3;
    const INST_RECEBER_CONFORME_INSTRUCOES_NO_PROPRIO_TITULO = 5;
    const INST_DEVOLVER_APOS_10_DIAS_DO_VENCIMENTO = 6;
    const INST_DEVOLVER_APOS_15_DIAS_DO_VENCIMENTO = 7;
    const INST_DEVOLVER_APOS_20_DIAS_DO_VENCIMENTO = 8;
    const INST_PROTESTAR = 9;
    const INST_NAO_PROTESTAR = 10;
    const INST_DEVOLVER_APOS_25_DIAS_DO_VENCIMENTO = 11;
    const INST_DEVOLVER_APOS_35_DIAS_DO_VENCIMENTO = 12;
    const INST_DEVOLVER_APOS_40_DIAS_DO_VENCIMENTO = 13;
    const INST_DEVOLVER_APOS_45_DIAS_DO_VENCIMENTO = 14;
    const INST_DEVOLVER_APOS_50_DIAS_DO_VENCIMENTO = 15;
    const INST_DEVOLVER_APOS_55_DIAS_DO_VENCIMENTO = 16;
    const INST_DEVOLVER_APOS_60_DIAS_DO_VENCIMENTO = 17;
    const INST_DEVOLVER_APOS_90_DIAS_DO_VENCIMENTO = 18;
    const INST_NAO_RECEBER_APOS_05_DIAS_DO_VENCIMENTO = 19;
    const INST_NAO_RECEBER_APOS_10_DIAS_DO_VENCIMENTO = 20;
    const INST_NAO_RECEBER_APOS_15_DIAS_DO_VENCIMENTO = 21;
    const INST_NAO_RECEBER_APOS_20_DIAS_DO_VENCIMENTO = 22;
    const INST_NAO_RECEBER_APOS_25_DIAS_DO_VENCIMENTO = 23;
    const INST_NAO_RECEBER_APOS_30_DIAS_DO_VENCIMENTO = 24;
    const INST_NAO_RECEBER_APOS_35_DIAS_DO_VENCIMENTO = 25;
    const INST_NAO_RECEBER_APOS_40_DIAS_DO_VENCIMENTO = 26;
    const INST_NAO_RECEBER_APOS_45_DIAS_DO_VENCIMENTO = 27;
    const INST_NAO_RECEBER_APOS_50_DIAS_DO_VENCIMENTO = 28;
    const INST_NAO_RECEBER_APOS_55_DIAS_DO_VENCIMENTO = 29;
    const INST_IMPORTANCIA_DE_DESCONTO_POR_DIA = 30;
    const INST_NAO_RECEBER_APOS_60_DIAS_DO_VENCIMENTO = 31;
    const INST_NAO_RECEBER_APOS_90_DIAS_DO_VENCIMENTO = 32;
    const INST_CONCEDER_ABATIMENTO_REF_PIS_PASEP_COFIN_CSSL_MESMO_APOS_VENCIMENTO = 33;
    const INST_PROTESTAR_APOS_XX_DIAS_CORRIDOS_DO_VENCIMENTO = 34;
    const INST_PROTESTAR_APOS_XX_DIAS_UTEIS_DO_VENCIMENTO = 35;
    const INST_RECEBER_ATE_O_ULTIMO_DIA_DO_MES_DE_VENCIMENTO = 37;
    const INST_CONCEDER_DESCONTO_MESMO_APOS_VENCIMENTO = 38;
    const INST_NAO_RECEBER_APOS_O_VENCIMENTO = 39;
    const INST_CONCEDER_DESCONTO_CONFORME_NOTA_DE_CREDITO = 40;
    const INST_PROTESTO_PARA_FINS_FALIMENTARES = 42;
    const INST_SUJEITO_A_PROTESTO_SE_NAO_FOR_PAGO_NO_VENCIMENTO = 43;
    const INST_IMPORTANCIA_POR_DIA_DE_ATRASO_A_PARTIR_DE_DDMMAA = 44;
    const INST_TEM_DIA_DA_GRACA = 45;
    const INST_DISPENSAR_JUROS_COMISSAO_DE_PERMANENCIA = 47;
    const INST_RECEBER_SOMENTE_COM_A_PARCELA_ANTERIOR_QUITADA = 51;
    const INST_EFETUAR_O_PAGAMENTO_SOMENTE_ATRAVES_DESTE_BOLETO_E_NA_REDE_BANCARIA = 52;
    const INST_APOS_VENCIMENTO_PAGAVEL_SOMENTE_NA_EMPRESA = 54;
    const INST_SOMAR_VALOR_DO_TITULO_AO_VALOR_DO_CAMPO_MORA_MULTA_CASO_EXISTA = 57;
    const INST_DEVOLVER_APOS_365_DIAS_DE_VENCIDO = 58;
    const INST_COBRANCA_NEGOCIADA_PAGAVEL_SOMENTE_POR_ESTE_BOLETO_NA_REDE_BANCARIA = 59;
    const INST_TITULO_ENTREGUE_EM_PENHOR_EM_FAVOR_DO_BENEFICIARIO_ACIMA = 61;
    const INST_TITULO_TRANSFERIDO_A_FAVOR_DO_BENEFICIARIO = 62;
    const INST_ENTRADA_EM_NEGATIVACAO_EXPRESSA_IMPRIME_SUJEITO_A_NEGATIVACAO_APOS_O_VENCIMENTO = 66;
    const INST_NAO_NEGATIVAR_INIBE_A_ENTRADA_EM_NEGATIVACAO_EXPRESSA = 67;
    const INST_VALOR_DA_IDA_ENGLOBA_MULTA_DE_10PERC_PRO_RATA = 78;
    const INST_COBRAR_JUROS_APOS_15_DIAS_DA_EMISSAO_PARA_TITULOS_COM_VENCIMENTO_A_VISTA = 79;
    const INST_PAGAMENTO_EM_CHEQUE_SOMENTE_RECEBER_COM_CHEQUE_DE_EMISSAO_DO_PAGADOR = 80;
    const INST_OPERACAO_REF_A_VENDOR = 83;
    const INST_APOS_VENCIMENTO_CONSULTAR_A_AGENCIA_BENEFICIARIO = 84;
    const INST_ANTES_DO_VENCIMENTO_OU_APOS_15_DIAS_PAGAVEL_SOMENTE_EM_NOSSA_SEDE = 86;
    const INST_NAO_RECEBER_ANTES_DO_VENCIMENTO = 88;
    const INST_NO_VENCIMENTO_PAGAVEL_EM_QUALQUER_AGENCIA_BANCARIA = 90;
    const INST_NAO_RECEBER_APOS_XX_DIAS_DO_VENCIMENTO = 91;
    const INST_DEVOLVER_APOS_XX_DIAS_DO_VENCIMENTO = 92;
    const INST_MENSAGENS_NOS_BOLETOS_COM_30_POSICOES = 93;
    const INST_MENSAGENS_NOS_BOLETOS_COM_40_POSICOES = 94;
}
